CREATE TABLE SPLITEX(
ID INT PRIMARY KEY IDENTITY(1,1),
NAME VARCHAR(50) NOT NULL)

INSERT INTO SPLITEX (NAME) VALUES('John,Jeremy,Jack')

SELECT * FROM SPLITEX

INSERT INTO SPLITEX (NAME) VALUES('YASH,HERO,LUFFY')
INSERT INTO SPLITEX (NAME) VALUES('KUMAR,MOUSE,33')
INSERT INTO SPLITEX (NAME) VALUES('THAKUR,AKSHAY,TIME')
EXEC GETSPILTNAME